import {
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
} from "docx";
import type { Workspace } from "../workspace.js";
import type { ReportOptions } from "../services.js";
import { buildExportPackage } from "../services.js";

function cell(text: string, bold = false) {
  return new TableCell({
    width: { size: 2200, type: WidthType.DXA },
    children: [
      new Paragraph({
        children: [new TextRun({ text, bold, size: 18, font: "Calibri" })],
      }),
    ],
  });
}

/** Client DOCX export from structured casefile data. */
export async function buildDocxBuffer(
  ws: Workspace,
  engagementId: string,
  options: ReportOptions = {},
): Promise<Buffer> {
  const pkg = buildExportPackage(ws, engagementId, {
    visibility: options.visibility ?? "active",
    confirmedOnly: options.confirmedOnly,
  });
  const eng = pkg.engagement;
  const findings = pkg.findings as Array<{
    title: string;
    severity: string;
    status: string;
    host: string | null;
    path: string | null;
    description: string | null;
    impact: string | null;
    remediation: string | null;
    cwe: string | null;
    cve: string | null;
  }>;

  const children: (Paragraph | Table)[] = [];

  children.push(
    new Paragraph({
      text: eng.name,
      heading: HeadingLevel.TITLE,
    }),
  );
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Client: ${eng.client || "—"}  ·  Type: ${eng.type}  ·  Status: ${eng.status}`,
          italics: true,
          size: 20,
        }),
      ],
    }),
  );
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: options.confirmedOnly
            ? "Profile: confirmed findings only"
            : "Profile: active findings (archived excluded)",
          size: 18,
          color: "666666",
        }),
      ],
    }),
  );
  children.push(new Paragraph({ text: "" }));

  children.push(
    new Paragraph({ text: "Executive summary", heading: HeadingLevel.HEADING_1 }),
  );
  children.push(
    new Paragraph({
      text: `This document summarizes ${findings.length} finding(s) exported from Sheaf. Validate all issues before client delivery.`,
    }),
  );

  children.push(
    new Paragraph({ text: "Findings overview", heading: HeadingLevel.HEADING_1 }),
  );

  if (findings.length === 0) {
    children.push(new Paragraph({ text: "No findings in this export profile." }));
  } else {
    children.push(
      new Table({
        width: { size: 9000, type: WidthType.DXA },
        rows: [
          new TableRow({
            children: [
              cell("Severity", true),
              cell("Status", true),
              cell("Title", true),
              cell("Host", true),
            ],
          }),
          ...findings.map(
            (f) =>
              new TableRow({
                children: [
                  cell(f.severity),
                  cell(f.status),
                  cell(f.title),
                  cell(f.host || "—"),
                ],
              }),
          ),
        ],
      }),
    );
  }

  for (const f of findings) {
    children.push(new Paragraph({ text: "" }));
    children.push(
      new Paragraph({
        text: f.title,
        heading: HeadingLevel.HEADING_2,
      }),
    );
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `${f.severity.toUpperCase()} · ${f.status}${f.host ? ` · ${f.host}` : ""}${f.path ?? ""}`,
            size: 18,
            color: "666666",
          }),
        ],
      }),
    );
    if (f.cwe || f.cve) {
      children.push(
        new Paragraph({
          text: [f.cwe, f.cve].filter(Boolean).join(" · "),
        }),
      );
    }
    children.push(new Paragraph({ text: "Description", heading: HeadingLevel.HEADING_3 }));
    children.push(new Paragraph({ text: f.description || "—" }));
    children.push(new Paragraph({ text: "Impact", heading: HeadingLevel.HEADING_3 }));
    children.push(new Paragraph({ text: f.impact || "—" }));
    children.push(new Paragraph({ text: "Remediation", heading: HeadingLevel.HEADING_3 }));
    children.push(new Paragraph({ text: f.remediation || "—" }));
  }

  children.push(new Paragraph({ text: "" }));
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: "Generated by Sheaf — local-first engagement casefile.",
          italics: true,
          size: 16,
          color: "888888",
        }),
      ],
    }),
  );

  const doc = new Document({
    sections: [{ children }],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}
